version: '3.9'
services:
    product-db:
        container_name: product-db
        image: postgres:latest
        restart: unless-stopped
        ports:
            - 5434:5432
        environment:
            POSTGRES_PASSWORD: 'postgres'
